import {
  awesomeBooks,
  bookstore,
  dota2Heros,
  leaderboard,
  siribox,
  spaceTravellers,
  todo,
} from '../../assets/images/images';

const projectDatas = [
  {
    id: 1,
    title: 'Dota2 Heros',
    description:
      'Dota2 Heroes" is a responsive web application designed to help users explore and learn about all the heroes featured in the DOTA2 game. The project was developed using React.js and Redux, and it leverages the OpenDota API for data retrieval. I served as the sole developer for this project.',
    image: dota2Heros,
    live_link: 'https://dota2-heros.netlify.app',
    github_link: 'https://github.com/K0ppai/dota2_heros',
    responsive: 'Responsive',
    tech: ['React', 'Redux', 'TailwindCss', 'Rest API'],
    built_date: 'August 2023',
    development_type: 'Front-End Development',
    goal: 'The goal of this project was to use react components, react props, react router, connect react and redux, handle events in a react app, write integration tests with a react testing library, use styles in a react app, use react life cycle methods, apply react best practices and language style guides in code, use store, actions and reducers in react.',
    key_feature:
      'This app provides search feature which allows users to have the capability to search for their favorite heroes by name. One of the standout features that I take great pride in is the hero animation, which you can experience when visiting the hero detail page.',
    lesson_learned:
      'One of the notable challenges I encountered during this project was implementing real-time dynamic rendering. Ensuring that the app updated and displayed results as users typed hero names was a complex task. However, this project served as a valuable learning experience, equipping me with the skills to master dynamic rendering in web applications.',
  },
  {
    id: 2,
    title: 'SiriBox',
    description:
      'SiriBox is a website that showcases a collection of movies and TV shows. It serves as the capstone project for the Microverse JavaScript curriculum. Developed using JavaScript, HTML, CSS, and Webpack, it utilizes API data to display content. Users can interact by liking and commenting on the website and filter shows according to genres.',
    image: siribox,
    live_link: 'https://siribox.netlify.app',
    github_link: 'https://github.com/K0ppai/SiriBox',
    tech: ['JavaScript', 'Bootstrap', 'Rest API'],
    responsive: 'Responsive',
    built_date: 'July 2023',
    development_type: 'Front-End Development',
    goal: 'project goal',
    key_feature: 'Project key feature',
    lesson_learned: 'Lessons learned during building project',
  },
  {
    id: 3,
    title: 'Leaderboard',
    description:
      'Leaderboard is an app that you can use to input your scores. It displays all of the user inputs from anywhere from best score to worst score.',
    image: leaderboard,
    live_link: 'https://leaderboard-list.netlify.app',
    github_link: 'https://github.com/K0ppai/leaderboard-list-app',
    tech: ['JavaScript', 'Bootstrap', 'POST API'],
    responsive: 'Responsive',
    built_date: 'June 2023',
    development_type: 'Front-End Development',
    goal: 'project goal',
    key_feature: 'Project key feature',
    lesson_learned: 'Lessons learned during building project',
  },
  {
    id: 4,
    title: 'Space Travellers',
    description:
      'Space Travellers is a web application.Users can interact with the application by joining a mission, leaving a mission,reserving rockets and viewing the list of missions and rockets.',
    image: spaceTravellers,
    live_link: 'https://space-travellers-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/space_travelers',
    tech: ['React', 'Redux', 'Rest API'],
    responsive: 'Desktop',
    built_date: 'July 2023',
    development_type: 'Front-End Development',
    goal: 'project goal',
    key_feature: 'Project key feature',
    lesson_learned: 'Lessons learned during building project',
  },
  {
    id: 5,
    title: 'Bookstore',
    description:
      '[Bookstore] is a web application that allows users to add and remove books from a Book list. The project was built with React.js.',
    image: bookstore,
    live_link: 'https://bookstore-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/bookstore_app',
    tech: ['React', 'Redux', 'Rest API'],
    responsive: 'Desktop',
    built_date: 'July 2023',
    development_type: 'Front-End Development',
    goal: 'project goal',
    key_feature: 'Project key feature',
    lesson_learned: 'Lessons learned during building project',
  },
  {
    id: 6,
    title: 'Todo List',
    description: 'This is project 1',
    image: todo,
    live_link: 'https://todo-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/to-do-list-app',
    tech: ['JavaScript', 'Local Storage'],
    responsive: 'Responsive',
    built_date: 'June 2023',
    development_type: 'Front-End Development',
    goal: 'project goal',
    key_feature: 'Project key feature',
    lesson_learned: 'Lessons learned during building project',
  },
  {
    id: 7,
    title: 'Awesome Books',
    description: 'This is project 1',
    image: awesomeBooks,
    live_link: 'https://awesomebooks-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/awesome-books-ES6',
    tech: ['JavaScript', 'Local Storage'],
    responsive: 'Desktop',
    built_date: 'June 2023',
    development_type: 'Front-End Development',
    goal: 'project goal',
    key_feature: 'Project key feature',
    lesson_learned: 'Lessons learned during building project',
  },
];
export default projectDatas;
