import { awesomeBooks, bookstore, dota2Heros, leaderboard, siribox, spaceTravellers, todo } from '../../assets/images/images';

const projectDatas = [
  {
    id: 1,
    title: 'Dota2 Heros',
    description: 'This is project 1',
    image: dota2Heros,
    live_link: 'https://dota2-heros.netlify.app',
    github_link: 'https://github.com/K0ppai/dota2_heros',
    tech: ['React', 'Redux', 'Tailwindcss', 'Rest API', 'Responsive'],
    built_date: 'August 2023',
  },
  {
    id: 2,
    title: 'SiriBox',
    description: 'This is project 1',
    image: siribox,
    live_link: 'https://siribox.netlify.app',
    github_link: 'https://github.com/K0ppai/SiriBox',
    tech: ['JavaScript', 'Bootstrap', 'Rest API', 'Responsive'],
    built_date: 'July 2023',
  },
  {
    id: 3,
    title: 'Leaderboard',
    description: 'This is project 1',
    image: leaderboard,
    live_link: 'https://leaderboard-list.netlify.app',
    github_link: 'https://github.com/K0ppai/leaderboard-list-app',
    tech: ['JavaScript', 'Bootstrap', 'POST API', 'Responsive'],
    built_date: 'June 2023',
  },
  {
    id: 4,
    title: 'Space Travellers',
    description: 'This is project 1',
    image: spaceTravellers,
    live_link: 'https://space-travellers-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/space_travelers',
    tech: ['React', 'Redux', 'Rest API', 'Desktop'],
    built_date: 'July 2023',
  },
  {
    id: 5,
    title: 'Bookstore',
    description: 'This is project 1',
    image: bookstore,
    live_link: 'https://bookstore-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/bookstore_app',
    tech: ['React', 'Redux', 'Rest API', 'Desktop'],
    built_date: 'July 2023',
  },
  {
    id: 6,
    title: 'Todo List',
    description: 'This is project 1',
    image: todo,
    live_link: 'https://todo-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/to-do-list-app',
    tech: ['JavaScript', 'Local Storage'],
    built_date: 'June 2023',
  },
  {
    id: 1,
    title: 'Awesome Books',
    description: 'This is project 1',
    image: awesomeBooks,
    live_link: 'https://awesomebooks-koppai.netlify.app',
    github_link: 'https://github.com/K0ppai/awesome-books-ES6',
    tech: ['JavaScript', 'Local Storage'],
    built_date: 'June 2023',
  },
];
export default projectDatas;
